// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelryAuction.Data.Models;

public partial class AuctionResult
{
    public int UserId { get; set; }

    public long? Payment { get; set; }

    public int AucId { get; set; }

    public virtual AuctionRequest Auc { get; set; }

    public virtual Customer User { get; set; }
}