// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelryAuction.Data.Models;

public partial class AuctionRequestDetail
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public decimal? ProductStartBidAmount { get; set; }

    public decimal? MinBidIncrement { get; set; }

    public int? SellerId { get; set; }

    public virtual ICollection<AuctionRequest> AuctionRequests { get; set; } = new List<AuctionRequest>();

    public virtual ICollection<AuctionSession> AuctionSessions { get; set; } = new List<AuctionSession>();
}