// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelryAuction.Data.Models;

public partial class PaymentMethod
{
    public int PaymentMethodId { get; set; }

    public string PaymentMethodDescription { get; set; }

    public virtual ICollection<AuctionRequest> AuctionRequests { get; set; } = new List<AuctionRequest>();
}